export const teamPages = {
    current: {
        heroImageAlt: 'TMUCSA Full Team Photo',
        heroImageUrl:
            'https://firebasestorage.googleapis.com/v0/b/tmucsa-6eb8a.firebasestorage.app/o/team-images%2Fteam-hero.webp?alt=media&token=8a05e600-82ef-4c44-aa6f-34412eb978b3',
        title: 'OUR TEAM',
        yearLabel: '2025-2026',
        sections: {
            executives: {
                backgroundImageAlt: 'Executive team photo',
                backgroundImageUrl:
                    'https://firebasestorage.googleapis.com/v0/b/tmucsa-6eb8a.firebasestorage.app/o/team-images%2Fexecs%2Fexec-team.webp?alt=media&token=e58d6ef1-1b8a-4a08-bbf1-d3ef271b66e1',
                memberIds: ['jason-su', 'audrey-chen', 'kayley-wong', 'avril-huang', 'vera-hoang', 'ivy-zou', 'sophia-khuu', 'kathy-luu'],
                name: 'EXECUTIVES',
                order: 1,
                type: 'executive',
            },
            marketing: {
                backgroundImageAlt: 'Marketing team photo',
                backgroundImageUrl:
                    'https://firebasestorage.googleapis.com/v0/b/tmucsa-6eb8a.firebasestorage.app/o/team-images%2Fmarketing%2FMARKETINGTEAM.webp?alt=media&token=bd477aa4-875f-4131-b895-4e1e3a5d58a3',
                memberIds: [
                    'kathy-lu',
                    'ashleigh-llacer',
                    'amanda-hu',
                    'dominic-chen',
                    'yuze-situ',
                    'braeden-lau',
                    'joseph-leung',
                    'ashley-bazzano',
                    'vivian-lam',
                    'stephanie-ho',
                    'janessa-to',
                    'kathy-bui',
                    'shawn-xu',
                    'tiffany-fong',
                    'avery-pain',
                    'jacqueline-to',
                ],
                name: 'MARKETING',
                order: 2,
                subteams: [
                    {
                        id: 'marketing-vp',
                        imageAlt: 'Marketing VP',
                        imageUrl:
                            'https://firebasestorage.googleapis.com/v0/b/tmucsa-6eb8a.firebasestorage.app/o/team-images%2Fmarketing%2FVPMARKETING.webp?alt=media&token=021119f7-14d9-4708-ba35-87185b22e937',
                        memberIds: ['kathy-lu'],
                        name: 'VP',
                        order: 1,
                    },
                    {
                        id: 'marketing-graphics',
                        imageAlt: 'Graphics team',
                        imageUrl: 'GRAPHICS IMAGE',
                        memberIds: ['ashleigh-llacer', 'yuze-situ', 'tiffany-fong', 'jacqueline-to'],
                        name: 'GRAPHICS',
                        order: 2,
                    },
                    {
                        id: 'marketing-associates',
                        imageAlt: 'Marketing associates team photo',
                        imageUrl:
                            'https://firebasestorage.googleapis.com/v0/b/tmucsa-6eb8a.firebasestorage.app/o/team-images%2Fmarketing%2F_MARKETINGASSOCIATES_0449.webp?alt=media&token=5e7a018a-0c10-4f95-a198-cfae0e3e8f48',
                        memberIds: ['vivian-lam', 'stephanie-ho'],
                        name: 'ASSOCIATES',
                        order: 3,
                    },
                    {
                        id: 'marketing-cams',
                        imageAlt: 'Marketing cams team photo',
                        imageUrl:
                            'https://firebasestorage.googleapis.com/v0/b/tmucsa-6eb8a.firebasestorage.app/o/team-images%2Fmarketing%2FCAMSTEAM.webp?alt=media&token=2dfe3630-7b9d-4148-a0ef-70ce38961693',
                        memberIds: ['amanda-hu', 'braeden-lau', 'ashley-bazzano', 'janessa-to', 'kathy-bui', 'shawn-xu', 'avery-pain'],
                        name: 'CAMS',
                        order: 4,
                    },
                    {
                        id: 'marketing-web-devs',
                        imageAlt: 'Marketing web dev team photo',
                        imageUrl:
                            'https://firebasestorage.googleapis.com/v0/b/tmucsa-6eb8a.firebasestorage.app/o/team-images%2Fmarketing%2FWEBDEV.webp?alt=media&token=264ce6a2-f7d4-4918-94ea-eba6860a219b',
                        memberIds: ['dominic-chen', 'joseph-leung'],
                        name: 'WEB DEVS',
                        order: 5,
                    },
                ],
                type: 'department',
            },
            events: {
                backgroundImageAlt: 'Events team photo',
                backgroundImageUrl:
                    'https://firebasestorage.googleapis.com/v0/b/tmucsa-6eb8a.firebasestorage.app/o/team-images%2Fmarketing%2FMARKETINGTEAM.webp?alt=media&token=bd477aa4-875f-4131-b895-4e1e3a5d58a3',
                memberIds: [
                    'kathy-lu',
                    'ashleigh-llacer',
                    'amanda-hu',
                    'dominic-chen',
                    'yuze-situ',
                    'braeden-lau',
                    'joseph-leung',
                    'ashley-bazzano',
                    'vivian-lam',
                    'stephanie-ho',
                    'janessa-to',
                    'kathy-bui',
                    'shawn-xu',
                    'tiffany-fong',
                    'avery-pain',
                    'jacqueline-to',
                ],
                name: 'Events',
                order: 2,
                subteams: [
                    {
                        id: 'marketing-vp',
                        imageAlt: 'Marketing VP',
                        imageUrl:
                            'https://firebasestorage.googleapis.com/v0/b/tmucsa-6eb8a.firebasestorage.app/o/team-images%2Fmarketing%2FVPMARKETING.webp?alt=media&token=021119f7-14d9-4708-ba35-87185b22e937',
                        memberIds: ['kathy-lu'],
                        name: 'VP',
                        order: 1,
                    },
                    {
                        id: 'marketing-graphics',
                        imageAlt: 'Graphics team',
                        imageUrl: 'GRAPHICS IMAGE',
                        memberIds: ['ashleigh-llacer', 'yuze-situ', 'tiffany-fong', 'jacqueline-to'],
                        name: 'GRAPHICS',
                        order: 2,
                    },
                    {
                        id: 'marketing-associates',
                        imageAlt: 'Marketing associates team photo',
                        imageUrl:
                            'https://firebasestorage.googleapis.com/v0/b/tmucsa-6eb8a.firebasestorage.app/o/team-images%2Fmarketing%2F_MARKETINGASSOCIATES_0449.webp?alt=media&token=5e7a018a-0c10-4f95-a198-cfae0e3e8f48',
                        memberIds: ['vivian-lam', 'stephanie-ho'],
                        name: 'ASSOCIATES',
                        order: 3,
                    },
                    {
                        id: 'marketing-cams',
                        imageAlt: 'Marketing cams team photo',
                        imageUrl:
                            'https://firebasestorage.googleapis.com/v0/b/tmucsa-6eb8a.firebasestorage.app/o/team-images%2Fmarketing%2FCAMSTEAM.webp?alt=media&token=2dfe3630-7b9d-4148-a0ef-70ce38961693',
                        memberIds: ['amanda-hu', 'braeden-lau', 'ashley-bazzano', 'janessa-to', 'kathy-bui', 'shawn-xu', 'avery-pain'],
                        name: 'CAMS',
                        order: 4,
                    },
                    {
                        id: 'marketing-web-devs',
                        imageAlt: 'Marketing web dev team photo',
                        imageUrl:
                            'https://firebasestorage.googleapis.com/v0/b/tmucsa-6eb8a.firebasestorage.app/o/team-images%2Fmarketing%2FWEBDEV.webp?alt=media&token=264ce6a2-f7d4-4918-94ea-eba6860a219b',
                        memberIds: ['dominic-chen', 'joseph-leung'],
                        name: 'WEB DEVS',
                        order: 5,
                    },
                ],
                type: 'department',
            },
        },
    },
}

export const members = {
    'jason-su': {
        displayName: 'Jason Su',
        executiveOrder: 1,
        firstName: 'Jason',
        headshotAlt: 'President photo solo',
        headshotUrl:
            'https://firebasestorage.googleapis.com/v0/b/tmucsa-6eb8a.firebasestorage.app/o/team-images%2Fexecs%2Fjason.webp?alt=media&token=631f85fc-de90-4b7c-80c5-43ae68d47729',
        isActive: true,
        isExecutive: true,
        lastName: 'Su',
        program: 'Computer Engineering',
        roleTitle: 'President',
        year: 4,
    },
    'audrey-chen': {
        displayName: 'Audrey Chen',
        executiveOrder: 2,
        firstName: 'Audrey',
        headshotAlt: '',
        headshotUrl: 'https://firebasestorage.googleapis.com/v0/b/tmucsa-6eb8a.firebasestorage.app/o/team-images%2Fexecs%2Faudrey.webp?alt=media&token=ac7dda33-f779-49ba-affe-663d8eb4b8cc',
        isActive: true,
        isExecutive: true,
        lastName: 'Chen',
        program: 'Business Management',
        roleTitle: 'External EVP',
        year: 3,
    },
    'kayley-wong': {
        displayName: 'Kayley Wong',
        executiveOrder: 3,
        firstName: 'Kayley',
        headshotAlt: '',
        headshotUrl: 'https://firebasestorage.googleapis.com/v0/b/tmucsa-6eb8a.firebasestorage.app/o/team-images%2Fexecs%2Fkayley.webp?alt=media&token=ac7dda33-f779-49ba-affe-663d8eb4b8cc',
        isActive: true,
        isExecutive: true,
        lastName: 'Wong',
        program: 'Business Management',
        roleTitle: 'Internal EVP',
        year: 3,
    },
    'avril-huang': {
        displayName: 'Avril Huang',
        executiveOrder: 5,
        firstName: 'Avril',
        headshotAlt: '',
        headshotUrl: 'https://firebasestorage.googleapis.com/v0/b/tmucsa-6eb8a.firebasestorage.app/o/team-images%2Fexecs%2Favril.webp?alt=media&token=12345678-1234-1234-1234-123456789012',
        isActive: true,
        isExecutive: true,
        lastName: 'Huang',
        program: 'Biomedical Science',
        roleTitle: 'VP Events',
        year: 2,
    },
    'vera-hoang': {
        displayName: 'Vera Hoang',
        executiveOrder: 8,
        firstName: 'Vera',
        headshotAlt: '',
        headshotUrl: 'https://firebasestorage.googleapis.com/v0/b/tmucsa-6eb8a.firebasestorage.app/o/team-images%2Fexecs%2Fvera.webp?alt=media&token=12345678-1234-1234-1234-123456789012',
        isActive: true,
        isExecutive: true,
        lastName: 'Hoang',
        program: 'Accounting and Finance',
        roleTitle: 'VP Internals',
        year: 4,
    },
    'ivy-zou': {
        displayName: 'Ivy Zou',
        executiveOrder: 6,
        firstName: 'Ivy',
        headshotAlt: '',
        headshotUrl: 'https://firebasestorage.googleapis.com/v0/b/tmucsa-6eb8a.firebasestorage.app/o/team-images%2Fexecs%2Fivy.webp?alt=media&token=12345678-1234-1234-1234-123456789012',
        isActive: true,
        isExecutive: true,
        lastName: 'Zou',
        program: 'Computer Science',
        roleTitle: 'VP Finance',
        year: 3,
    },
    'sophia-khuu': {
        displayName: 'Sophia Khuu',
        executiveOrder: 6,
        firstName: 'Sophia',
        headshotAlt: '',
        headshotUrl: 'https://firebasestorage.googleapis.com/v0/b/tmucsa-6eb8a.firebasestorage.app/o/team-images%2Fexecs%2Fsophia.webp?alt=media&token=12345678-1234-1234-1234-123456789012',
        isActive: true,
        isExecutive: true,
        lastName: 'Khuu',
        program: 'Communications',
        roleTitle: 'VP Corporate Relations',
        year: 2,
    },
    'kathy-luu': {
        displayName: 'Kathy Luu',
        executiveOrder: 4,
        firstName: 'Kathy',
        headshotAlt: '',
        headshotUrl: 'https://firebasestorage.googleapis.com/v0/b/tmucsa-6eb8a.firebasestorage.app/o/team-images%2Fexecs%2Fkathy.webp?alt=media&token=3b53190c-ae39-4f64-86f3-eb0a9c2940fd',
        isActive: true,
        isExecutive: true,
        lastName: 'Luu',
        program: 'Marketing Management',
        roleTitle: 'VP Marketing',
        year: 5,
    },
    'ashleigh-llacer': {
        displayName: 'Ashleigh Llacer',
        executiveOrder: 0,
        firstName: 'Ashleigh',
        headshotAlt: '',
        headshotUrl: '',
        isActive: true,
        isExecutive: false,
        lastName: 'Llacer',
        program: 'Graphic Design',
        roleTitle: 'Graphic Designer',
        year: 3,
    },
    'amanda-hu': {
        displayName: 'Amanda Hu',
        executiveOrder: 0,
        firstName: 'Amanda',
        headshotAlt: '',
        headshotUrl: '',
        isActive: true,
        isExecutive: false,
        lastName: 'Hu',
        program: 'Media Production',
        roleTitle: 'Videographer',
        year: 4,
    },
    'dominic-chen': {
        displayName: 'Dominic Chen',
        executiveOrder: 0,
        firstName: 'Dominic',
        headshotAlt: '',
        headshotUrl: '',
        isActive: true,
        isExecutive: false,
        lastName: 'Chen',
        program: 'Computer Science',
        roleTitle: 'Web Developer',
        year: 4,
    },
    'yuze-situ': {
        displayName: 'Yuze Situ',
        executiveOrder: 0,
        firstName: 'Yuze',
        headshotAlt: '',
        headshotUrl: '',
        isActive: true,
        isExecutive: false,
        lastName: 'Situ',
        program: 'Graphic Design',
        roleTitle: 'Graphic Designer',
        year: 2,
    },
    'braeden-lau': {
        displayName: 'Braeden Lau',
        executiveOrder: 0,
        firstName: 'Braeden',
        headshotAlt: '',
        headshotUrl: '',
        isActive: true,
        isExecutive: false,
        lastName: 'Lau',
        program: 'Media Production',
        roleTitle: 'Photographer',
        year: 3,
    },
    'joseph-leung': {
        displayName: 'Joseph Leung',
        executiveOrder: 0,
        firstName: 'Joseph',
        headshotAlt: '',
        headshotUrl: '',
        isActive: true,
        isExecutive: false,
        lastName: 'Leung',
        program: 'Computer Engineering',
        roleTitle: 'Web Developer',
        year: 2,
    },
    'ashley-bazzano': {
        displayName: 'Ashley Bazzano',
        executiveOrder: 0,
        firstName: 'Ashley',
        headshotAlt: '',
        headshotUrl: '',
        isActive: true,
        isExecutive: false,
        lastName: 'Bazzano',
        program: 'Media Production',
        roleTitle: 'Videographer',
        year: 2,
    },
    'vivian-lam': {
        displayName: 'Vivian Lam',
        executiveOrder: 0,
        firstName: 'Vivian',
        headshotAlt: '',
        headshotUrl: '',
        isActive: true,
        isExecutive: false,
        lastName: 'Lam',
        program: 'Psychology',
        roleTitle: 'Associate',
        year: 3,
    },
    'stephanie-ho': {
        displayName: 'Stephanie Ho',
        executiveOrder: 0,
        firstName: 'Stephanie',
        headshotAlt: '',
        headshotUrl: '',
        isActive: true,
        isExecutive: false,
        lastName: 'Ho',
        program: 'Business Management',
        roleTitle: 'Associate',
        year: 1,
    },
    'janessa-to': {
        displayName: 'Janessa To',
        executiveOrder: 0,
        firstName: 'Janessa',
        headshotAlt: '',
        headshotUrl: '',
        isActive: true,
        isExecutive: false,
        lastName: 'To',
        program: 'Film Studies',
        roleTitle: 'Photographer',
        year: 4,
    },
    'kathy-bui': {
        displayName: 'Kathy Bui',
        executiveOrder: 0,
        firstName: 'Kathy',
        headshotAlt: '',
        headshotUrl: '',
        isActive: true,
        isExecutive: false,
        lastName: 'Bui',
        program: 'Media Production',
        roleTitle: 'Videographer',
        year: 2,
    },
    'shawn-xu': {
        displayName: 'Shawn Xu',
        executiveOrder: 0,
        firstName: 'Shawn',
        headshotAlt: '',
        headshotUrl: '',
        isActive: true,
        isExecutive: false,
        lastName: 'Xu',
        program: 'Computer Science',
        roleTitle: 'Photographer',
        year: 5,
    },
    'tiffany-fong': {
        displayName: 'Tiffany Fong',
        executiveOrder: 0,
        firstName: 'Tiffany',
        headshotAlt: '',
        headshotUrl: '',
        isActive: true,
        isExecutive: false,
        lastName: 'Fong',
        program: 'Graphic Design',
        roleTitle: 'Graphic Designer',
        year: 4,
    },
    'avery-pain': {
        displayName: 'Avery Pain',
        executiveOrder: 0,
        firstName: 'Avery',
        headshotAlt: '',
        headshotUrl: '',
        isActive: true,
        isExecutive: false,
        lastName: 'Pain',
        program: 'Media Production',
        roleTitle: 'Videographer',
        year: 1,
    },
    'jacqueline-to': {
        displayName: 'Jacqueline To',
        executiveOrder: 0,
        firstName: 'Jacqueline',
        headshotAlt: '',
        headshotUrl: '',
        isActive: true,
        isExecutive: false,
        lastName: 'To',
        program: 'Graphic Design',
        roleTitle: 'Graphic Designer',
        year: 3,
    },
}